print('happy birthday ammalu')
print()
print('       happy happy')
print("      happy  birthday")
print('     happy    birthday ')
print('    happy       birthday')
print('   happy  happy   birthday')
print('  happy            birthday')
print(' happy              birthday')
print('happy                 birthday')
input()